version: '2'

services:
  zoo1:
    image: zookeeper:3.4.11
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
#    network_mode: "host"
    networks:
      default:
        ipv4_address: 172.18.3.3
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      
      
  zoo2:
    image: zookeeper:3.4.11
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2182:2181
#    network_mode: "host"
    networks:
      default:
        ipv4_address: 172.18.3.4
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
      
      
  zoo3:
    image: zookeeper:3.4.11
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2183:2181
#    network_mode: "host"
    networks:
      default:
        ipv4_address: 172.20.3.5
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888

networks:
  default:
    external:
      name: shadowlands-network
#networks:
#  zk-net:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.20.1.0/24
#          gateway: 172.20.1.1
